[jinja2:suite.rc]

# General run options
WC_URBAN=true
nregns=1

# Nested region 1
rg01_name="HM_small"
rg01_centre=-26.225,134.025

# Resolution 1 (era driving data)
rg01_rs01_name="era5"
rg01_rs01_npts=380,480

# Resolution 2 (BARRA-R2 resolution)
rg01_rs02_name="BARRA-R2"
rg01_rs02_npts=360,460

# # Resolution 3 (4.4 km inner domain)
# rg01_rs03_name="p04"
# rg01_rs03_delta=0.04,0.04
# rg01_rs03_npts=1068,1348
# rg01_rs03_offset=0.0,0.0